# remote_theme: bencentra/centrarium
remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll
plugins: 
- jekyll-remote-theme
title: Mudcrab Darwin harbour crossing
description: An underwater crossing of Darwin harbour in an electric Landcruiser

defaults:
  -
    scope:
      path: ""
    values:
      background: "/img/mudcrab.jpg"
      author: "matt"