
# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-remote-theme
- jekyll-paginate
- jekyll-seo-tag
# - jekyll-sitemap
# - jekyll-mentions
# - jekyll-redirect-from
# - jekyll-feed
# - jekyll-commonmark
# - jekyll-include-cache
# - jemoji

# Set theme
remote_theme: "daattali/beautiful-jekyll"

# Site settings
url: 'https://underwaterlandcruiser.com'
#baseurl: ''
title: Mudcrab Darwin harbour crossing
description: An underwater crossing of Darwin harbour in an electric Landcruiser
timezone: Australia/Melbourne
permalink: pretty
logo: "/assets/logos/mudcrab@200px.png"

# Pagination
paginate: 5
paginate_path: "posts/page:num"

# Navigation Links
navbar-links:
  Technical: "tech_specs"
  Project: "project"
  Team: "team"
  Media: "media"


# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

    
