
# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-remote-theme
- jekyll-paginate
- jekyll-seo-tag
# - jekyll-sitemap
# - jekyll-mentions
# - jekyll-redirect-from
# - jekyll-feed
# - jekyll-commonmark
# - jekyll-include-cache
# - jemoji

# Set theme
remote_theme: daviddarnes/alembic@main

# Site settings
#url: 'https://'
#baseurl: ''
title: Mudcrab Darwin harbour crossing
description: An underwater crossing of Darwin harbour in an electric Landcruiser
timezone: Australia/Melbourne
permalink: pretty
logo: "/assets/logos/mudcrab@200px.png"

# Pagination
paginate: 5
paginate_path: "posts/page:num"

navigation_header:
- title: Home
  url: /
- title: About
  url: /about
- title: Media
  url: /media
- title: Posts
  url: /posts

navigation_footer:
- title: Underwater landcruiser
  url: https://mudcrab-landcruiser.github.io
- title: Back to top
  url: "#top"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  96: "/assets/logos/mudcrab@96px.png"
  192: "/assets/logos/mudcrab@192px.png"
  512: "/assets/logos/mudcrab@512px.png"
  
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap
